[author.mao-ni]
name = "Mao Ni"
alt_names = ["猫腻"]

[author.gu-zhen-ren]
name = "Gu Zhen Ren"
alt_names = ["蛊真人"]

[author.angry-squid]
name = "Angry Squid"
alt_names = ["愤怒的乌贼"]

[author.angry-squirrel]
name = "Angry Squirrel"
alt_names = ["愤怒的松鼠"]

[author.golden-jasmine]
name = "Golden Jasmine"
alt_names = ["金色茉莉花"]

[author.cuttlefish-that-loves-diving]
name = "Cuttlefish That Loves Diving"
alt_names = ["爱潜水的乌贼"]

[author.er-gen]
name = "Er Gen"
alt_names = ["耳根"]
links = [
  { title = "novelupdates", url = "https://www.novelupdates.com/nauthor/er-gen/" },
]

[author.fang-xiang]
name = "Fang Xiang"
alt_names = ["方想"]

[author.chaos]
name = "Chaos"
alt_names = ["乱"]

[author.tang-jia-san-shao]
name = "Tang Jia San Shao"
alt_names = ["唐家三少"]

[author.can-fix-air-conditioners]
name = "Can Fix Air-Conditioners"
alt_names = ["我会修空调"]

[author.thefirstdefier]
name = "TheFirstDefier"

[author.kirill-klevanski]
name = "Kirill Klevanski"

[author.ostensible-mammal]
name = "OstensibleMammal"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/293473" },
]

[author.rinoz]
name = "RinoZ"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/97247" },
]

[author.guilty-three]
name = "Guiltythree"

[author.uraniumphoenix]
name = "UraniumPhoenix"

[author.seersucker]
name = "seersucker"

[author.azalea-ellis]
name = "Azalea Ellis"

[author.doctorhepa]
name = "DoctorHepa"

[author.casualfarmer]
name = "Casualfarmer"

[author.cerim]
name = "Cerim"

[author.actus]
name = "Actus"

[author.clarke]
name = "J.M. Clarke"
alt_names = ["U Juggernaut"]

[author.thundamoo]
name = "Thundamoo"

[author.strungbound]
name = "Strungbound"

[author.mecanimus]
name = "Mecanimus"

[author.turtleme]
name = "TurtleMe"

[author.dads-bedtime-stories]
name = "Dads Bedtime Stories"

[author.chirolu]
name = "Chirolu"

[author.silverlinings]
name = "SilverLinings"

[author.xkarnation]
name = "XKARNATION"

[author.kawahara-reki]
name = "Kawahara Reki"

[author.robert-blaise]
name = "Robert Blaise"

[author.mark-arrows]
name = "Mark Arrows"

[author.wildbow]
name = "Wildbow"

[author.dakota-krout]
name = "Dakota Krout"

[author.sinnoa]
name = "Sinnoa"

[author.randombluecat]
name = "RandomBlueCat"

[author.the-plagiarist]
name = "The Plagiarist"

[author.chen-dong]
name = "Chen Dong"
alt_names = ["辰东"]

[author.yu-ryeo-han]
name = "Yu Ryeo Han"
alt_names = ["유려한"]

[author.the-enlightened-master-crouching-cow]
name = "The Enlightened Master Crouching Cow"
alt_names = ["卧牛真人"]

[author.mikage-eiji]
name = "Mikage Eiji"

[author.nocturnal-stranger]
name = "Nocturnal Stranger"
alt_names = ["厄夜怪客"]

[author.ya-boy]
name = "Ya Boy"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/202632" },
]

[author.god-loves-the-world]
name = "God Loves The World"
alt_names = ["神仙爱凡尘"]

[author.necariin]
name = "Necariin"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/122394" },
]

[author.x-rhoden-x]
name = "X-RHODEN-X"

[author.fast-food-restaurant]
name = "Fast Food Restaurant"
alt_names = ["快餐店"]

[author.chugong]
name = "Chugong"
alt_names = ["추공"]

[author.xin-feng]
name = "Xin Feng"
alt_names = ["新丰"]

[author.legend-of-the-paladin]
name = "Legend of the Paladin"
alt_names = ["圣骑士的传说"]

[author.foxtail-quill]
name = "Foxtail Quill"
alt_names = ["狐尾的笔"]
links = [
  { title = "novelupdates", url = "https://www.novelupdates.com/nauthor/foxtail-quill/" },
]

[author.maxime-j-durand]
name = "Maxime J. Durand"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/107213" },
]

[author.jin-nai]
name = "Jin Nai"
alt_names = ["今奈"]
links = [
  { title = "novelupdates", url = "https://www.novelupdates.com/nauthor/jin-nai/" },
]

[author.warby-picus]
name = "Warby Picus"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/261544" },
]

[author.flossindune]
name = "Flossindune"
links = [
  { title = "royalorad", url = "https://www.royalroad.com/profile/299461" },
]

[author.quiet-support]
name = "Quiet Support"
alt_names = ["安静捧场"]
links = [
  { title = "novelupdates", url = "https://www.novelupdates.com/nauthor/quiet-support/" },
]

[author.cluelessrr]
name = "CluelessRR"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/471901" },
]

[author.arthur-wordsmith]
name = "Arthur Wordsmith"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/323423" },
]

[author.pu-jie-tianxian]
name = "Pū jiē tiānxiàn"
alt_names = ["扑街天线"]
links = [
  { title = "novelupdates", url = "https://www.novelupdates.com/nauthor/%e6%89%91%e8%a1%97%e5%a4%a9%e7%ba%bf/" },
]

[author.warmaisach]
name = "Warmaisach"
links = [
  { title = "webnovel", url = "https://m.webnovel.com/profile/3286855836" },
]

[author.exploding-small-latte]
name = "Exploding Small Latte"
alt_names = ["爆炸小拿铁"]
links = [
  { title = "novelupdates", url = "https://www.novelupdates.com/nauthor/exploding-small-latte/" },
]

[author.arcanecadence]
name = "ArcaneCadence"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/729989" },
]

[author.the-whitest-crow]
name = "The Whitest Crow"
alt_names = ["最白的乌鸦"]
links = [
  { title = "novelupdates", url = "https://www.novelupdates.com/nauthor/%e6%9c%80%e7%99%bd%e7%9a%84%e4%b9%8c%e9%b8%a6/" },
]

[author.emes]
name = "EmEs"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/235726" },
]

[author.colin-j-d-crooks]
name = "Colin J.D. Crooks"
links = [
  { title = "goodreads", url = "https://www.goodreads.com/author/show/21106941.Colin_J_D_Crooks" },
]

[author._172]
name = "_172"
links = [
  { title = "novelupdates", url = "https://www.novelupdates.com/nauthor/_172/" },
]

[author.tk523]
name = "TK523"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/112902" },
]

[author.zaifyr]
name = "zaifyr"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/285838" },
]

[author.cornman]
name = "Cornman"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/394190" },
]

[author.the-one-who-was]
name = "The_One_Who_Was"
links = [
  { title = "webnovel", url = "https://www.webnovel.com/profile/4324450853" },
]

[author.lit-homunculus]
name = "Lit Homunculus"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/56125" },
]

[author.macronomicon]
name = "Macronomicon"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/100060" },
]

[author.crane-by-the-moonlit-pond]
name = "Crane by the Moonlit Pond"
alt_names = ["鹤守月满池"]
links = [
  { title = "novelupdates", url = "https://www.novelupdates.com/nauthor/crane-by-the-moonlit-pond/" },
]

[author.nicholas_sansbury_smith]
name = "Nicholas Sansbury Smith"
links = [
  { title = "aethonbooks", url = "https://aethonbooks.com/book-author/nicholas-sansbury-smith/" },
]

[author.scott_alexander]
name = "Scott Alexander"
links = [
  { title = "goodreads", url = "https://www.goodreads.com/author/show/10866248.Scott_Alexander" },
]

[author.erraticerrata]
name = "ErraticErrata"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/21586" },
]

[authors.palt]
name = "Palt"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/35937" },
]

[author.phill_tucker]
name = "Phill Tucker"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/73941" },
]

[author.slaughterbot]
name = "SlaughterBot"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/413099" },
]

[author.mikasane]
name = "Mikasane"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/244859" },
]

[author.voravora]
name = "VoraVora"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/236517" },
]

[author.quickduckling]
name = "QuickDuckling"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/472328" },
]

[author."一辈子小说家"]
name = "一辈子小说家"
links = [
  { title = "novelupdates", url = "https://www.novelupdates.com/nauthor/%e4%b8%80%e8%be%88%e5%ad%90%e5%b0%8f%e8%af%b4%e5%ae%b6/" },
]

[author."姬叉"]
name = "姬叉"
links = [
  { title = "novelupdates", url = "https://www.novelupdates.com/nauthor/%e5%a7%ac%e5%8f%89/" },
]

[author."窗边的鸽子"]
name = "窗边的鸽子"
links = [
  { title = "novelupdates", url = "https://www.novelupdates.com/nauthor/%e7%aa%97%e8%be%b9%e7%9a%84%e9%b8%bd%e5%ad%90/" },
]

[author."熊狼狗"]
name = "熊狼狗"
links = [
  { title = "novelupdates", url = "https://www.novelupdates.com/nauthor/%e7%86%8a%e7%8b%bc%e7%8b%97/" },
]

[author.joroboros]
name = "Joroboros"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/115230" },
]

[author.silv3rtongue]
name = "Silv3rtongue"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/418109" },
]

[author."纯洁滴小龙"]
name = "纯洁滴小龙"
links = [
  { title = "novelupdates", url = "https://www.novelupdates.com/nauthor/%e7%ba%af%e6%b4%81%e6%bb%b4%e5%b0%8f%e9%be%99/" },
]

[author."三藏的左轮"]
name = "三藏的左轮"
links = [
  { title = "wtrlab", url = "https://wtr-lab.com/en/author/%E4%B8%89%E8%97%8F%E7%9A%84%E5%B7%A6%E8%BD%AE" },
]

[author.offering-flowers-before-the-buddha]
name = "Offering flowers before the Buddha"
links = []

[author."季越人"]
name = "季越人"
links = [
  { title = "novelupdates", url = "https://www.novelupdates.com/nauthor/%e5%ad%a3%e8%b6%8a%e4%ba%ba/" },
]

[author.tsukumizu]
name = "Tsukumizu"
alt_names = ["つくみず"]
links = [
  { title = "wikipedia", url = "https://en.wikipedia.org/wiki/Tsukumizu" },
]

[author.wizardly_dude]
name = "Wizardly Dude"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/559659" },
]

[author.lokithequick]
name = "LokiTheQuick"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/456668" },
]

[author.markarrows]
name = "Mark Arrows"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/150899" },
]

[author.jpwrites]
name = "JPwrites "
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/9705" },
]

[author.cashen]
name = "Jman8763 C. Ashen"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/210709" },
]

[author.disheveledvagabond]
name = "DisheveledVagabond "
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/192594" },
]

[author.cognosticon]
name = "Cognosticon"
links = [
  { title = "royalroad", url = "https://www.royalroad.com/profile/270595" },
]
